name: client
description: Glints fullstack assignment client app.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    dio: ^4.0.1
    flutter_svg:
    flutter_dotenv: ^5.0.2
    http: ^0.13.3
    flutter_secure_storage: ^4.2.0
    jwt_decode: ^0.3.1
    flutter_bloc: ^8.0.1
    shimmer: ^2.0.0
    time_picker_widget: ^1.0.0+10

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/icons/
        - .env
